docker-build-composer:
  stage: build
  allow_failure: true
  # Use the official docker image.
  image: docker:latest
  #only: 
  #  - main
  services:
    - docker:dind
  before_script:
    # - echo "${GID}" > "${HOME}/.kube/config"
    - cd app/back/dockerfiles
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull --build-arg GID=${GID} --build-arg UID=${UID} -t "$CI_REGISTRY_IMAGE${tag}" -f composer.dockerfile .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

# include:
#   - local: ".gitlab/.gitlab-ci_service1_composer.yml"
#   - local: ".gitlab/.gitlab-ci_service2_elasticsearch.yml"
#   - local: ".gitlab/.gitlab-ci_service3_nginx.yml"
#   - local: ".gitlab/.gitlab-ci_service4_php.yml"
#   - local: ".gitlab/.gitlab-ci_service5_front.yml"
